### ISSUE TITLE
add CODEOFCONDUCT.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [aquasecurity/linux-bench#27]
Add codeofconduct.md file . The code of conduct does appear at the time of making a PR(on the side, like below).
I believe that it should be a part of the repo itself.
Happy to open a PR as part of hacktoberfest!
![Capture](https://user-images.githubusercontent.com/25405707/66603568-16cd8680-ebca-11e9-8f7d-6e39c3cf6d79.PNG)

**Comment by pwrmvspark** [comment]
Hi @Parikshit-Hooda, I'd like to work on this issue. Thanks!

**Comment by lizrice** [comment]
Please don't do this, we already have a code of conduct that is common across all the aquasecurity projects. Leaving this open in the hope that it will stop Hacktoberfest folks from trying to do it again...
